// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: auth_srv/proto/auth.proto

package shop_auth_srv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for User service

type UserService interface {
	// 根据用户id请求设置token
	SetTokenByUserId(ctx context.Context, in *CSTokenSet, opts ...client.CallOption) (*SCTokenSet, error)
	// 根据用户id请求清理token
	ClearTokenByUserId(ctx context.Context, in *CSTokenClear, opts ...client.CallOption) (*SCTokenClear, error)
	// 根据用户id获取token
	GetTokenByUserId(ctx context.Context, in *CSTokenGet, opts ...client.CallOption) (*SCTokenGet, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "shop.auth.srv"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) SetTokenByUserId(ctx context.Context, in *CSTokenSet, opts ...client.CallOption) (*SCTokenSet, error) {
	req := c.c.NewRequest(c.name, "User.SetTokenByUserId", in)
	out := new(SCTokenSet)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) ClearTokenByUserId(ctx context.Context, in *CSTokenClear, opts ...client.CallOption) (*SCTokenClear, error) {
	req := c.c.NewRequest(c.name, "User.ClearTokenByUserId", in)
	out := new(SCTokenClear)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetTokenByUserId(ctx context.Context, in *CSTokenGet, opts ...client.CallOption) (*SCTokenGet, error) {
	req := c.c.NewRequest(c.name, "User.GetTokenByUserId", in)
	out := new(SCTokenGet)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	// 根据用户id请求设置token
	SetTokenByUserId(context.Context, *CSTokenSet, *SCTokenSet) error
	// 根据用户id请求清理token
	ClearTokenByUserId(context.Context, *CSTokenClear, *SCTokenClear) error
	// 根据用户id获取token
	GetTokenByUserId(context.Context, *CSTokenGet, *SCTokenGet) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		SetTokenByUserId(ctx context.Context, in *CSTokenSet, out *SCTokenSet) error
		ClearTokenByUserId(ctx context.Context, in *CSTokenClear, out *SCTokenClear) error
		GetTokenByUserId(ctx context.Context, in *CSTokenGet, out *SCTokenGet) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) SetTokenByUserId(ctx context.Context, in *CSTokenSet, out *SCTokenSet) error {
	return h.UserHandler.SetTokenByUserId(ctx, in, out)
}

func (h *userHandler) ClearTokenByUserId(ctx context.Context, in *CSTokenClear, out *SCTokenClear) error {
	return h.UserHandler.ClearTokenByUserId(ctx, in, out)
}

func (h *userHandler) GetTokenByUserId(ctx context.Context, in *CSTokenGet, out *SCTokenGet) error {
	return h.UserHandler.GetTokenByUserId(ctx, in, out)
}
