// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth_srv/proto/auth.proto

package shop_auth_srv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 错误码
type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cda7fc51984e070, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

// token设置
type CSTokenSet struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSTokenSet) Reset()         { *m = CSTokenSet{} }
func (m *CSTokenSet) String() string { return proto.CompactTextString(m) }
func (*CSTokenSet) ProtoMessage()    {}
func (*CSTokenSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cda7fc51984e070, []int{1}
}

func (m *CSTokenSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSTokenSet.Unmarshal(m, b)
}
func (m *CSTokenSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSTokenSet.Marshal(b, m, deterministic)
}
func (m *CSTokenSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSTokenSet.Merge(m, src)
}
func (m *CSTokenSet) XXX_Size() int {
	return xxx_messageInfo_CSTokenSet.Size(m)
}
func (m *CSTokenSet) XXX_DiscardUnknown() {
	xxx_messageInfo_CSTokenSet.DiscardUnknown(m)
}

var xxx_messageInfo_CSTokenSet proto.InternalMessageInfo

func (m *CSTokenSet) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type SCTokenSet struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SCTokenSet) Reset()         { *m = SCTokenSet{} }
func (m *SCTokenSet) String() string { return proto.CompactTextString(m) }
func (*SCTokenSet) ProtoMessage()    {}
func (*SCTokenSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cda7fc51984e070, []int{2}
}

func (m *SCTokenSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SCTokenSet.Unmarshal(m, b)
}
func (m *SCTokenSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SCTokenSet.Marshal(b, m, deterministic)
}
func (m *SCTokenSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SCTokenSet.Merge(m, src)
}
func (m *SCTokenSet) XXX_Size() int {
	return xxx_messageInfo_SCTokenSet.Size(m)
}
func (m *SCTokenSet) XXX_DiscardUnknown() {
	xxx_messageInfo_SCTokenSet.DiscardUnknown(m)
}

var xxx_messageInfo_SCTokenSet proto.InternalMessageInfo

func (m *SCTokenSet) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *SCTokenSet) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SCTokenSet) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// token清理
type CSTokenClear struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSTokenClear) Reset()         { *m = CSTokenClear{} }
func (m *CSTokenClear) String() string { return proto.CompactTextString(m) }
func (*CSTokenClear) ProtoMessage()    {}
func (*CSTokenClear) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cda7fc51984e070, []int{3}
}

func (m *CSTokenClear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSTokenClear.Unmarshal(m, b)
}
func (m *CSTokenClear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSTokenClear.Marshal(b, m, deterministic)
}
func (m *CSTokenClear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSTokenClear.Merge(m, src)
}
func (m *CSTokenClear) XXX_Size() int {
	return xxx_messageInfo_CSTokenClear.Size(m)
}
func (m *CSTokenClear) XXX_DiscardUnknown() {
	xxx_messageInfo_CSTokenClear.DiscardUnknown(m)
}

var xxx_messageInfo_CSTokenClear proto.InternalMessageInfo

func (m *CSTokenClear) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SCTokenClear struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SCTokenClear) Reset()         { *m = SCTokenClear{} }
func (m *SCTokenClear) String() string { return proto.CompactTextString(m) }
func (*SCTokenClear) ProtoMessage()    {}
func (*SCTokenClear) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cda7fc51984e070, []int{4}
}

func (m *SCTokenClear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SCTokenClear.Unmarshal(m, b)
}
func (m *SCTokenClear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SCTokenClear.Marshal(b, m, deterministic)
}
func (m *SCTokenClear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SCTokenClear.Merge(m, src)
}
func (m *SCTokenClear) XXX_Size() int {
	return xxx_messageInfo_SCTokenClear.Size(m)
}
func (m *SCTokenClear) XXX_DiscardUnknown() {
	xxx_messageInfo_SCTokenClear.DiscardUnknown(m)
}

var xxx_messageInfo_SCTokenClear proto.InternalMessageInfo

func (m *SCTokenClear) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

// token获取
type CSUserIdGet struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSUserIdGet) Reset()         { *m = CSUserIdGet{} }
func (m *CSUserIdGet) String() string { return proto.CompactTextString(m) }
func (*CSUserIdGet) ProtoMessage()    {}
func (*CSUserIdGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cda7fc51984e070, []int{5}
}

func (m *CSUserIdGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSUserIdGet.Unmarshal(m, b)
}
func (m *CSUserIdGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSUserIdGet.Marshal(b, m, deterministic)
}
func (m *CSUserIdGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSUserIdGet.Merge(m, src)
}
func (m *CSUserIdGet) XXX_Size() int {
	return xxx_messageInfo_CSUserIdGet.Size(m)
}
func (m *CSUserIdGet) XXX_DiscardUnknown() {
	xxx_messageInfo_CSUserIdGet.DiscardUnknown(m)
}

var xxx_messageInfo_CSUserIdGet proto.InternalMessageInfo

func (m *CSUserIdGet) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SCUserIdGet struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SCUserIdGet) Reset()         { *m = SCUserIdGet{} }
func (m *SCUserIdGet) String() string { return proto.CompactTextString(m) }
func (*SCUserIdGet) ProtoMessage()    {}
func (*SCUserIdGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cda7fc51984e070, []int{6}
}

func (m *SCUserIdGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SCUserIdGet.Unmarshal(m, b)
}
func (m *SCUserIdGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SCUserIdGet.Marshal(b, m, deterministic)
}
func (m *SCUserIdGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SCUserIdGet.Merge(m, src)
}
func (m *SCUserIdGet) XXX_Size() int {
	return xxx_messageInfo_SCUserIdGet.Size(m)
}
func (m *SCUserIdGet) XXX_DiscardUnknown() {
	xxx_messageInfo_SCUserIdGet.DiscardUnknown(m)
}

var xxx_messageInfo_SCUserIdGet proto.InternalMessageInfo

func (m *SCUserIdGet) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *SCUserIdGet) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*Error)(nil), "shop.auth.srv.Error")
	proto.RegisterType((*CSTokenSet)(nil), "shop.auth.srv.CSTokenSet")
	proto.RegisterType((*SCTokenSet)(nil), "shop.auth.srv.SCTokenSet")
	proto.RegisterType((*CSTokenClear)(nil), "shop.auth.srv.CSTokenClear")
	proto.RegisterType((*SCTokenClear)(nil), "shop.auth.srv.SCTokenClear")
	proto.RegisterType((*CSUserIdGet)(nil), "shop.auth.srv.CSUserIdGet")
	proto.RegisterType((*SCUserIdGet)(nil), "shop.auth.srv.SCUserIdGet")
}

func init() { proto.RegisterFile("auth_srv/proto/auth.proto", fileDescriptor_6cda7fc51984e070) }

var fileDescriptor_6cda7fc51984e070 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0x87, 0x93, 0xb6, 0x29, 0xbc, 0x93, 0xbe, 0x50, 0x86, 0x22, 0x69, 0x7a, 0x29, 0x6b, 0x0f,
	0xc5, 0x43, 0x0a, 0xed, 0xcd, 0x9b, 0x0d, 0x52, 0x14, 0x0f, 0x9a, 0xd5, 0xb3, 0x44, 0xb3, 0x12,
	0xb1, 0xb8, 0x65, 0xb3, 0x29, 0xf4, 0x6b, 0xfb, 0x09, 0x24, 0xb3, 0x21, 0x49, 0xff, 0x78, 0x10,
	0xbc, 0xed, 0x64, 0x9e, 0x3c, 0xf3, 0xcb, 0x4e, 0x60, 0x18, 0xe7, 0x3a, 0x7d, 0xce, 0xd4, 0x76,
	0xb6, 0x51, 0x52, 0xcb, 0x59, 0x51, 0x06, 0x74, 0xc4, 0xff, 0x59, 0x2a, 0x37, 0x01, 0x3d, 0xc8,
	0xd4, 0x96, 0x2d, 0xc0, 0xb9, 0x56, 0x4a, 0x2a, 0x44, 0xe8, 0xbc, 0xca, 0x44, 0x78, 0xf6, 0xd8,
	0x9e, 0x3a, 0x11, 0x9d, 0xf1, 0x0c, 0xba, 0x89, 0xd0, 0xf1, 0xfb, 0xda, 0x6b, 0x8d, 0xed, 0xe9,
	0xbf, 0xa8, 0xac, 0xd8, 0x04, 0x20, 0xe4, 0x8f, 0xf2, 0x43, 0x7c, 0x72, 0xa1, 0x0b, 0x2a, 0xcf,
	0x84, 0xba, 0x49, 0xe8, 0xdd, 0x76, 0x54, 0x56, 0xec, 0x0d, 0x80, 0x87, 0x15, 0x75, 0x01, 0x8e,
	0x28, 0x06, 0x11, 0xe4, 0xce, 0x07, 0xc1, 0x5e, 0x8e, 0x80, 0x42, 0x44, 0x06, 0x69, 0x18, 0x5b,
	0x4d, 0x23, 0x0e, 0xc0, 0xd1, 0x85, 0xcf, 0x6b, 0x53, 0x1c, 0x53, 0xb0, 0x09, 0xf4, 0xca, 0x34,
	0xe1, 0x5a, 0xc4, 0xaa, 0xa6, 0xec, 0x26, 0x75, 0x09, 0xbd, 0x32, 0x8d, 0xa1, 0x7e, 0x91, 0x87,
	0x9d, 0x83, 0x1b, 0xf2, 0x27, 0xca, 0xb0, 0x12, 0xfa, 0x87, 0x01, 0x0f, 0xe0, 0xf2, 0xb0, 0x86,
	0xfe, 0xe0, 0x7b, 0xe7, 0x5f, 0x36, 0x74, 0xae, 0x72, 0x9d, 0xe2, 0x2d, 0xf4, 0xb9, 0xd0, 0x94,
	0x7e, 0xb9, 0x33, 0x33, 0x70, 0x78, 0x60, 0xac, 0x37, 0xe2, 0x1f, 0xb6, 0xea, 0x35, 0x30, 0x0b,
	0xef, 0x01, 0xe9, 0x06, 0xf6, 0x6d, 0xa3, 0xd3, 0x36, 0x22, 0xfd, 0xd1, 0x69, 0x1f, 0x35, 0x99,
	0x85, 0x77, 0xd0, 0x5f, 0x09, 0x6d, 0x44, 0xcb, 0x1d, 0xb5, 0xd0, 0x3f, 0xf2, 0x55, 0x57, 0xe3,
	0xfb, 0x47, 0xba, 0xaa, 0xc7, 0xac, 0x97, 0x2e, 0xfd, 0xa7, 0x8b, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc4, 0xc0, 0xae, 0x8e, 0xc4, 0x02, 0x00, 0x00,
}
